services:
  - type: web
    name: psec-planning
    env: node
    region: Oregon
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: PORT
        value: "10000"
      - key: HOST
        value: "0.0.0.0"
      - key: CORS_ORIGIN
        value: "https://${RENDER_EXTERNAL_HOSTNAME}"
    healthCheckPath: /api/health
    autoDeploy: true
